"""create parking slots table

Revision ID: 7812896ae0ec
Revises: 2478da95df72
Create Date: 2026-08-04 15:09:34.793768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7812896ae0ec'
down_revision: Union[str, Sequence[str], None] = '2478da95df72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.String(length=20), nullable=False),
    sa.Column('slot_type', sa.Enum('STANDARD', 'BIKE', 'EV', 'HANDICAP', name='slottype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'RESERVED', 'OCCUPIED', name='slotstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['parking_floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'slot_number', name='uq_floor_slot_number')
    )
    op.create_index(op.f('ix_parking_slots_floor_id'), 'parking_slots', ['floor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_slots_floor_id'), table_name='parking_slots')
    op.drop_table('parking_slots')
    # ### end Alembic commands ###
